;//####################################################################
;//-------------------------Configuration.inc--------------------------
;//	Here are located all project configuration settings   
;//--------------------------------------------------------------------
;//   Author:		Haris Turkmanovic
;//   Email:		haris@etf.rs
;//   Version:	    1.0
;//   Date:         April 2019.
;//--------------------------------------------------------------------
;//#####################################################################

ConsoleXMax			EQU 80
ConsoleYMax			EQU 30
ButtonPollingTime	EQU 20

VerticalLineChar    EQU 219
HorizontalLineChar1  EQU 220
HorizontalLineChar2  EQU 223

;constants for speed setup
DelaySpeedConst EQU 10
DelaySpeedMinimum EQU 2
FreqDelay EQU 7